version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
